# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='城市'),
        ),
        migrations.AlterUniqueTogether(
            name='courseorg',
            unique_together=set([('name', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set([('org', 'name')]),
        ),
    ]
