# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190504_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(unique=True, upload_to='course/resource/%Y/%m', verbose_name='资源文件'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='章节名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='视频名'),
        ),
    ]
