# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190504_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='media/image/%Y/%m'),
        ),
    ]
