# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190508_1006'),
        ('users', '0005_auto_20190508_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_org',
            field=models.ManyToManyField(to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
