# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course_org',
            field=models.ManyToManyField(blank=True, null=True, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
